---
- name: Set VM hostname
  block:
  - hostname:
      name: "{{ vm_hostname }}"
  - lineinfile:
      path: /etc/hosts
      line: "127.0.0.1 {{ vm_hostname }}"
      insertbefore: BOF

- name: Enable sysstat
  shell: echo ENABLED="true" >> /etc/default/sysstat

- name: Disable message-of-the-day MOTD
  file:
    path: "/etc/update-motd.d"
    mode: 0644
    recurse: yes
