- name: Install necessary packages
  apt:
    force_apt_get: true
    update_cache: true
    name: "{{ packages }}"
    install_recommends: false
    state: present
  vars:
    packages:
      - vim-tiny
      - rsync
      - logrotate
      - rsyslog
      - tzdata
      - chrony

- name: Install OpenJDK JRE 8
  apt:
    name: "openjdk-8-jre-headless"
    state: present
  when: java_enabled
