- name: Install necessary packages
  apt:
    force_apt_get: yes
    name: "{{ packages }}"
    install_recommends: no
    state: present
  vars:
    packages:
      - vim-tiny
      - rsync
      - logrotate
      - rsyslog
      - python

- name: Install OpenJDK JRE 8
  apt:
    name: "openjdk-8-jre-headless"
    state: present
  when: (java_enabled == 'True')
