---
- include_tasks: uninstall.yml
  tags:
    - uninstall

- name: Fully upgrade Linux distribution 
  apt:
    force_apt_get: true
    upgrade: full
    update_cache: true
    autoclean: true
    autoremove: true
    purge: true
  when: upgrade_os_enabled
  register: os_updated
  tags:
    - upgrade

- name: Reboot server after updated OS 
  reboot:
  when: os_updated is changed

- include_tasks: install.yml
  tags:
    - install

- include_tasks: sysctl.yml
  tags:
    - sysctl

- include_tasks: configure.yml
  tags:
    - configs
