---
- include_tasks: install.yml
  tags:
    - install

- include_tasks: sysctl.yml
  tags:
    - sysctl

- include_tasks: configure.yml
  tags:
    - configs

- include_tasks: uninstall.yml
  tags:
    - uninstall
