- name: Uninstall unnecessary packages
  apt:
    force_apt_get: yes
    name: "{{ uninstall_packages }}"
    state: absent
    autoremove: yes
    autoclean: yes
    purge: yes
  register: uninstalled
